"""Generating candidate reference pictures in the Prepare step.

The shot list is drafted from the character's appearance description without a model: a fixed
set of angles, expressions, outfits, light and full-body shots, all editable before anything is
sent. Every shot shares one base description and one seed so the set stays consistent.

Each shot is classified and routed like any image request (PRD F6): Prohibited is refused
everywhere, NSFW goes to a local backend only, and the check fails closed. Nothing joins the
dataset on its own; the user keeps or discards each picture, and a kept one is recorded as
generated by the backend that made it.
"""
import asyncio
import contextlib
import random

from companion.characters import require_current
from companion.database import decode, encode, identifier, many, one
from companion.errors import DomainError, require
from companion.images import backends
from companion.images.adapters.base import AdapterError, ImageRequest, size_for
from companion.images.content import classify, stricter
from companion.images.jobs import image_settings
from companion.images.prompts import NEGATIVE
from companion.images.routing import eligible, route
from companion.images.storage import raw_directory, sniff
from companion.lora import files, references

# (key, label, shot, aspect). The shot follows the base description in each prompt.
SHOTS = (
    ('front', 'Front portrait', 'head and shoulders portrait facing the camera, neutral expression, plain light '
     'grey background, soft even light', 'portrait'),
    ('three_quarter', 'Three-quarter view', 'three-quarter view portrait, slight smile, plain background',
     'portrait'),
    ('profile', 'Profile', 'side profile portrait, plain background, soft window light', 'portrait'),
    ('over_shoulder', 'Over the shoulder', 'looking back over the shoulder, outdoors, overcast daylight',
     'portrait'),
    ('laughing', 'Laughing', 'laughing, close-up of the face, natural light', 'square'),
    ('thoughtful', 'Thoughtful', 'thoughtful expression, chin resting on one hand, indoors, warm lamp light',
     'square'),
    ('surprised', 'Surprised', 'surprised expression, eyebrows raised, close-up of the face', 'square'),
    ('full_studio', 'Full body: studio', 'full-body photo standing, whole outfit visible, plain studio background',
     'portrait'),
    ('full_walking', 'Full body: walking', 'full-body photo walking along a city sidewalk in everyday clothes',
     'portrait'),
    ('full_sitting', 'Full body: sitting', 'full-body photo sitting on a park bench in a casual outfit',
     'landscape'),
    ('outfit_smart', 'Outfit: smart', 'upper body, wearing smart clothes at an indoor event, soft light',
     'portrait'),
    ('outfit_home', 'Outfit: at home', 'upper body, wearing a comfortable sweater at home, morning light',
     'portrait'),
    ('golden_hour', 'Light: golden hour', 'medium shot outdoors at golden hour, warm backlight', 'landscape'),
    ('night', 'Light: night', 'medium shot at night under street lights', 'landscape'),
)
DEFAULT_STYLE = 'Natural photograph'
MAX_SHOTS = 40


def directory(database):
    return files.folder(database, 'generated')


def base_of(definition) -> str:
    appearance = ' '.join(definition.get('appearance', '').split()).rstrip('.')
    return f"{definition['name']}, {appearance}" if appearance else definition['name']


def compose(style, base, shot) -> str:
    return f"{(style or DEFAULT_STYLE).rstrip('.')}. {base.strip().rstrip('.')}, {shot.strip().rstrip('.')}."


def draft(database) -> dict:
    with database.connect() as connection:
        definition = require_current(connection)['version']['definition']
        style = image_settings(connection)['style']
    return {'base': base_of(definition), 'style': style or DEFAULT_STYLE, 'negative': NEGATIVE,
            'seed': random.SystemRandom().randrange(1, 2**31),
            'shots': [{'key': key, 'label': label, 'shot': shot, 'aspect': aspect}
                      for key, label, shot, aspect in SHOTS]}


def routable_backends(connection) -> list[dict]:
    return [backend for backend in backends.ordered(connection, enabled_only=True) if not backend['blocked_reason']]


def plan(connection, body) -> list[dict]:
    """Each shot's prompt, classification and destination, exactly as it would be sent."""
    definition = require_current(connection)['version']['definition']
    style = image_settings(connection)['style']
    candidates = routable_backends(connection)
    planned = []
    for shot in body.shots:
        prompt = compose(style, body.base, shot.shot)
        classification = classify({'prompt': prompt, 'negative': NEGATIVE,
                                   'appearance': definition.get('appearance', ''), 'marked_nsfw': body.marked_nsfw})
        decision = route(classification, candidates, body.backend_id)
        target = decision.target
        planned.append({'label': shot.label, 'shot': shot.shot, 'aspect': shot.aspect, 'prompt': prompt,
                        'tier': classification.tier, 'reasons': classification.reasons,
                        'route_reason': decision.reason, 'refusal': decision.refusal,
                        'backend': None if target is None else {'id': target['id'], 'label': target['label'],
                                                                 'kind': target['kind'],
                                                                 'local': backends.is_local(target)}})
    return planned


def preview(database, body) -> dict:
    with database.connect() as connection:
        return {'shots': plan(connection, body)}


def create(database, body) -> dict:
    require(body.shots, 'Add at least one shot.', 422)
    with database.connect(write=True) as connection:
        companion = require_current(connection)
        busy = connection.execute("SELECT 1 FROM lora_generations WHERE status='running' AND companion_id=?",
                                  (companion['id'],)).fetchone()
        require(busy is None, 'Pictures are already being generated. Wait for them or stop them first.', 409)
        planned = plan(connection, body)
        generation_id = identifier()
        timestamp = database.now()
        connection.execute("INSERT INTO lora_generations (id, companion_id, base, seed, status, created_at) "
                           "VALUES (?, ?, ?, ?, 'running', ?)",
                           (generation_id, companion['id'], body.base.strip(), body.seed, timestamp))
        for position, item in enumerate(planned):
            target = item['backend']
            refused = target is None
            connection.execute(
                'INSERT INTO lora_gen_images (id, generation_id, position, label, shot, prompt, negative, aspect, '
                'seed, classification, reasons, route_reason, backend_id, backend_label, backend_kind, status, '
                'error, finished_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)',
                (identifier(), generation_id, position, item['label'], item['shot'], item['prompt'], NEGATIVE,
                 item['aspect'], body.seed, item['tier'], encode(item['reasons']), item['route_reason'],
                 None if refused else target['id'], None if refused else target['label'],
                 None if refused else target['kind'], 'failed' if refused else 'queued',
                 item['refusal'] if refused else None, timestamp if refused else None))
    return get(database, generation_id)


def image_view(row) -> dict:
    return {**{key: value for key, value in row.items() if key != 'output_file'},
            'reasons': decode(row['reasons']), 'has_image': row['output_file'] is not None}


def view(connection, generation) -> dict:
    images = many(connection, 'SELECT * FROM lora_gen_images WHERE generation_id=? ORDER BY position',
                  (generation['id'],))
    counts = {status: sum(image['status'] == status for image in images)
              for status in ('queued', 'running', 'completed', 'failed', 'cancelled', 'interrupted')}
    counts['kept'] = sum(image['decision'] == 'kept' for image in images)
    return {**generation, 'counts': counts, 'images': [image_view(image) for image in images]}


def listing(database) -> list[dict]:
    with database.connect() as connection:
        companion = require_current(connection)
        return [view(connection, row) for row in many(
            connection, "SELECT * FROM lora_generations WHERE companion_id=? AND kind='dataset' "
                        'ORDER BY created_at DESC, rowid DESC',
            (companion['id'],))]


def get(database, generation_id) -> dict:
    with database.connect() as connection:
        companion = require_current(connection)
        return view(connection, one(connection, 'SELECT * FROM lora_generations WHERE id=? AND companion_id=?',
                                    (generation_id, companion['id'])))


def image_row(connection, image_id) -> dict:
    companion = require_current(connection)
    return one(connection, 'SELECT i.* FROM lora_gen_images i JOIN lora_generations g ON g.id = i.generation_id '
                           'WHERE i.id=? AND g.companion_id=?', (image_id, companion['id']))


def file_of(database, image_id):
    with database.connect() as connection:
        row = image_row(connection, image_id)
    require(row['output_file'] is not None, 'This picture has no file.', 404)
    return files.inside(directory(database), row['output_file'])


def source_note(image) -> str:
    made_with = image['model'] or image['backend_kind']
    seed = f", seed {image['used_seed']}" if image['used_seed'] is not None else ''
    return f"Generated by {image['backend_label']} ({made_with}{seed}). Prompt: {image['prompt']}"[:1000]


def kept_bytes(database, image, converted: bytes | None) -> bytes:
    """The stored output, or the interface's PNG copy when the backend returned WebP, which the
    trainer cannot read. The copy must have the same size as the stored output."""
    data = files.inside(directory(database), image['output_file']).read_bytes()
    kind, width, height = sniff(data)
    if kind in references.TYPES:
        return data
    if not converted:
        raise DomainError('This picture is WebP; the interface converts it to PNG before keeping it.', 422,
                          'convert')
    try:
        new_kind, new_width, new_height = sniff(converted)
    except AdapterError as error:
        raise DomainError('The converted copy is not an image.', 422) from error
    require(new_kind in references.TYPES and (new_width, new_height) == (width, height),
            'The converted copy does not match the generated picture.', 422)
    return converted


def keep(database, image_id, role, dhash=None, converted: bytes | None = None) -> dict:
    with database.connect() as connection:
        image = image_row(connection, image_id)
    require(image['status'] == 'completed' and image['output_file'], 'Only a finished picture can be kept.', 409)
    require(image['decision'] is None, 'This picture was already kept or discarded.', 409)
    data = kept_bytes(database, image, converted)
    added = references.add(database, data, f"{image['label']} (generated)", dhash)
    with database.connect(write=True) as connection:
        connection.execute("UPDATE lora_references SET rights='generated', source_note=?, role=?, updated_at=? "
                           'WHERE id=?', (source_note(image), role, database.now(), added['id']))
        connection.execute("UPDATE lora_gen_images SET decision='kept', reference_id=? WHERE id=?",
                           (added['id'], image_id))
    return get(database, image['generation_id'])


def discard(database, image_id) -> dict:
    with database.connect(write=True) as connection:
        image = image_row(connection, image_id)
        require(image['decision'] is None, 'This picture was already kept or discarded.', 409)
        connection.execute("UPDATE lora_gen_images SET decision='discarded', output_file=NULL WHERE id=?",
                           (image_id,))
    if image['output_file']:
        (directory(database) / image['output_file']).unlink(missing_ok=True)
    return get(database, image['generation_id'])


def recover(database):
    with database.connect(write=True) as connection:
        timestamp = database.now()
        connection.execute("UPDATE lora_gen_images SET status='interrupted', error='The app closed first.', "
                           "finished_at=? WHERE status IN ('queued', 'running')", (timestamp,))
        connection.execute("UPDATE lora_generations SET status='interrupted', finished_at=? WHERE status='running'",
                           (timestamp,))


class GenerationRunner:
    """Makes one set's pictures one at a time through the image backends. It shares the image
    runner's admission rules: a backend's job limit, the single Codex slot, and local ComfyUI
    waiting while a chat reply is written or a trainer holds the GPU."""

    def __init__(self, database, vault, images, pause=0.5):
        self.database = database
        self.vault = vault
        self.images = images
        self.pause = pause
        self.tasks: dict[str, asyncio.Task] = {}
        self.current: dict | None = None
        images.sharing.append(lambda: [self.current] if self.current else [])

    def start(self, generation_id) -> asyncio.Task:
        task = asyncio.get_running_loop().create_task(self.run(generation_id))
        self.tasks[generation_id] = task
        task.add_done_callback(lambda _task: self.tasks.pop(generation_id, None))
        return task

    async def run(self, generation_id):
        try:
            while (image := self.next_image(generation_id)) is not None:
                await self.render(image)
            self.close(generation_id, 'completed')
        except asyncio.CancelledError:
            self.close(generation_id, 'cancelled')
            raise

    def next_image(self, generation_id):
        with self.database.connect() as connection:
            generation = one(connection, 'SELECT status FROM lora_generations WHERE id=?', (generation_id,))
            if generation['status'] != 'running':
                return None
            image = connection.execute("SELECT * FROM lora_gen_images WHERE generation_id=? AND status='queued' "
                                       'ORDER BY position LIMIT 1', (generation_id,)).fetchone()
            return None if image is None else dict(image)

    def mark(self, image_id, **fields):
        columns = ', '.join(f'{key}=?' for key in fields)
        with self.database.connect(write=True) as connection:
            connection.execute(f'UPDATE lora_gen_images SET {columns} WHERE id=?', (*fields.values(), image_id))

    def fail(self, image_id, message):
        self.mark(image_id, status='failed', error=message, finished_at=self.database.now())

    def backend_problem(self, image, backend) -> str | None:
        if backend is None or not backend['enabled']:
            return 'The backend this picture was routed to is no longer enabled.'
        if backend['blocked_reason']:
            return f"{backend['label']} is stopped: {backend['blocked_reason']}"
        classification = classify({'prompt': image['prompt'], 'negative': image['negative']})
        classification.tier = stricter(classification.tier, image['classification'])
        if not eligible(classification, backend):
            return f"This picture is classified {classification.tier} and cannot go to {backend['label']}."
        return None

    def backend(self, image) -> dict | None:
        with self.database.connect() as connection:
            row = connection.execute('SELECT * FROM image_backends WHERE id=?', (image['backend_id'],)).fetchone()
        return None if row is None else dict(row)

    async def admitted(self, image) -> dict | None:
        """The backend once it has room; None (and the picture failed) when it can no longer take it."""
        while True:
            backend = self.backend(image)
            problem = self.backend_problem(image, backend)
            if problem:
                self.fail(image['id'], problem)
                return None
            if not self.images.busy(backend):
                return backend
            await asyncio.sleep(self.pause)

    def reference(self, image) -> bytes | None:
        """The finished picture this one follows (onboarding portraits). Raises when it is missing."""
        if image['follows'] is None:
            return None
        with self.database.connect() as connection:
            row = connection.execute('SELECT output_file FROM lora_gen_images WHERE generation_id=? AND position=?',
                                     (image['generation_id'], image['follows'])).fetchone()
        if row is None or row['output_file'] is None:
            raise LookupError(f"Picture {image['follows'] + 1} did not finish, so this one has nothing to follow.")
        return files.inside(directory(self.database), row['output_file']).read_bytes()

    async def render(self, image):
        try:
            reference = self.reference(image)
        except (LookupError, OSError) as error:
            self.fail(image['id'], str(error) if isinstance(error, LookupError) else 'The picture to follow is missing.')
            return
        backend = await self.admitted(image)
        if backend is None:
            return
        self.current = {'id': backend['id'], 'kind': backend['kind']}
        self.mark(image['id'], status='running', started_at=self.database.now())
        try:
            await self.generate(image, backend, reference)
        finally:
            self.current = None
            self.images.wake()

    async def generate(self, image, backend, reference=None):
        width, height = size_for(backend['kind'], image['aspect'])
        config = decode(backend['config'])
        key = self.vault.get(backend['credential_ref']) if backend['credential_ref'] else None
        request = ImageRequest(image['id'], image['prompt'], image['negative'], image['seed'], width, height,
                               backend, config, key, raw_directory(self.database), reference=reference)
        try:
            result = await self.images.adapters[backend['kind']].generate(request)
            kind, out_width, out_height = sniff(result.data)
            name = f"{image['id']}.{kind}"
            (directory(self.database) / name).write_bytes(result.data)
        except asyncio.CancelledError:
            self.mark(image['id'], status='cancelled', error='Cancelled.', finished_at=self.database.now())
            raise
        except AdapterError as error:
            if error.code == 'auth':
                backends.block(self.database, backend['id'], error.message)
            self.fail(image['id'], error.message)
            return
        except Exception as error:  # noqa: BLE001 - one failed picture is recorded, not hidden.
            self.fail(image['id'], f'The picture failed ({error}).')
            return
        if result.raw_path:
            with contextlib.suppress(OSError):
                result.raw_path.unlink()
        self.mark(image['id'], status='completed', output_file=name, width=out_width, height=out_height,
                  used_seed=result.seed, model=result.model or config.get('model'), workflow=result.workflow,
                  finished_at=self.database.now())

    def close(self, generation_id, status):
        with self.database.connect(write=True) as connection:
            timestamp = self.database.now()
            if status != 'completed':
                connection.execute("UPDATE lora_gen_images SET status='cancelled', error='Cancelled.', finished_at=? "
                                   "WHERE generation_id=? AND status IN ('queued', 'running')",
                                   (timestamp, generation_id))
            connection.execute("UPDATE lora_generations SET status=?, finished_at=? WHERE id=? AND status='running'",
                               (status, timestamp, generation_id))

    async def cancel(self, generation_id) -> dict:
        get(self.database, generation_id)
        task = self.tasks.get(generation_id)
        if task is None:
            self.close(generation_id, 'cancelled')
        else:
            task.cancel()
            with contextlib.suppress(asyncio.CancelledError):
                await task
        return get(self.database, generation_id)
