"""What clothes exist for the wardrobe (companion/life/wardrobe.py), written for this app: the pieces
for modern and earlier settings, colour palettes by style, the words that suggest a style, and what
each career wears to work."""

# piece, category, occasions, styles ('*' suits any), who ('f' feminine, 'm' masculine, '*' anyone),
# lowest pay tier that buys it, colour palette ('style' for the wearer's style colours, '' for none).
MODERN_PIECES = (
    ('crew-neck tee', 'top', 'ch', '*', '*', 0, 'style'),
    ('striped Breton top', 'top', 'c', 'classic preppy minimal', '*', 0, ''),
    ('cable-knit sweater', 'top', 'ch', 'cozy classic preppy', '*', 0, 'style'),
    ('oversized hoodie', 'top', 'ch', 'sporty cozy edgy', '*', 0, 'style'),
    ('flannel shirt', 'top', 'c', 'cozy vintage edgy', '*', 0, 'style'),
    ('button-down shirt', 'top', 'cw', 'classic preppy minimal', '*', 0, 'style'),
    ('oxford shirt', 'top', 'cw', 'preppy classic', '*', 0, 'style'),
    ('silk blouse', 'top', 'wo', 'classic minimal', 'f', 2, 'style'),
    ('blouse', 'top', 'cw', 'classic boho vintage', 'f', 0, 'style'),
    ('peasant blouse', 'top', 'c', 'boho', 'f', 0, 'style'),
    ('fitted turtleneck', 'top', 'cwo', 'minimal classic', '*', 0, 'style'),
    ('cardigan', 'top', 'cwh', 'cozy vintage preppy', '*', 0, 'style'),
    ('faded band tee', 'top', 'c', 'edgy vintage', '*', 0, ''),
    ('graphic tee', 'top', 'c', 'sporty edgy', '*', 0, 'style'),
    ('polo shirt', 'top', 'cw', 'preppy sporty', '*', 0, 'style'),
    ('henley', 'top', 'c', 'cozy minimal', '*', 0, 'style'),
    ('cashmere sweater', 'top', 'cwo', 'classic minimal', '*', 3, 'style'),
    ('wrap top', 'top', 'o', 'classic boho', 'f', 0, 'style'),
    ('sequined top', 'top', 'o', 'edgy classic', 'f', 1, 'style'),
    ('crisp dress shirt', 'top', 'wo', 'classic minimal preppy', 'm', 0, 'style'),
    ('knit vest', 'top', 'c', 'vintage preppy', '*', 0, 'style'),
    ('linen shirt', 'top', 'co', 'boho minimal', '*', 1, 'style'),
    ('straight-leg jeans', 'bottom', 'c', '*', '*', 0, 'denim'),
    ('skinny jeans', 'bottom', 'co', 'edgy sporty', '*', 0, 'denim'),
    ('wide-leg jeans', 'bottom', 'c', 'boho vintage', '*', 0, 'denim'),
    ('ripped jeans', 'bottom', 'co', 'edgy', '*', 0, 'denim'),
    ('chinos', 'bottom', 'cw', 'preppy classic minimal', '*', 0, 'style'),
    ('tailored trousers', 'bottom', 'wo', 'classic minimal', '*', 1, 'style'),
    ('wool slacks', 'bottom', 'w', 'classic preppy', '*', 1, 'style'),
    ('pleated midi skirt', 'bottom', 'cwo', 'classic vintage', 'f', 0, 'style'),
    ('denim skirt', 'bottom', 'c', 'vintage boho', 'f', 0, ''),
    ('flowy maxi skirt', 'bottom', 'c', 'boho', 'f', 0, 'style'),
    ('pencil skirt', 'bottom', 'w', 'classic', 'f', 1, 'style'),
    ('cargo pants', 'bottom', 'c', 'edgy sporty', '*', 0, 'style'),
    ('corduroy trousers', 'bottom', 'c', 'vintage cozy', '*', 0, 'style'),
    ('faux-leather trousers', 'bottom', 'o', 'edgy', '*', 1, ''),
    ('cotton shorts', 'bottom', 'c', '*', '*', 0, 'style'),
    ('linen trousers', 'bottom', 'c', 'boho minimal', '*', 1, 'style'),
    ('sundress', 'dress', 'c', 'boho cozy vintage', 'f', 0, 'style'),
    ('wrap dress', 'dress', 'wo', 'classic', 'f', 0, 'style'),
    ('little black dress', 'dress', 'o', 'classic minimal edgy', 'f', 0, ''),
    ('satin slip dress', 'dress', 'o', 'edgy minimal', 'f', 1, 'style'),
    ('sweater dress', 'dress', 'cw', 'cozy', 'f', 0, 'style'),
    ('floral midi dress', 'dress', 'co', 'boho vintage', 'f', 0, ''),
    ('shirt dress', 'dress', 'cw', 'preppy minimal', 'f', 0, 'style'),
    ('tea dress', 'dress', 'co', 'vintage', 'f', 0, 'style'),
    ('cocktail dress', 'dress', 'o', 'classic', 'f', 2, 'style'),
    ('evening gown', 'dress', 'o', 'classic', 'f', 3, 'style'),
    ('tailored suit', 'suit', 'wo', 'classic minimal preppy', '*', 1, 'style'),
    ('made-to-measure suit', 'suit', 'wo', 'classic', '*', 3, 'style'),
    ('blazer', 'layer', 'wo', 'classic preppy minimal', '*', 0, 'style'),
    ('denim jacket', 'layer', 'c', 'vintage boho edgy sporty', '*', 0, ''),
    ('leather jacket', 'layer', 'co', 'edgy vintage', '*', 1, 'leather'),
    ('bomber jacket', 'layer', 'c', 'sporty edgy', '*', 0, 'style'),
    ('suede jacket', 'layer', 'co', 'boho vintage', '*', 2, 'leather'),
    ('zip-up fleece', 'layer', 'c', 'sporty cozy', '*', 0, 'style'),
    ('wool coat', 'outerwear', 'k', 'classic minimal', '*', 1, 'style'),
    ('peacoat', 'outerwear', 'k', 'preppy classic vintage', '*', 0, 'style'),
    ('puffer jacket', 'outerwear', 'k', 'sporty cozy', '*', 0, 'style'),
    ('hooded parka', 'outerwear', 'k', '*', '*', 0, 'style'),
    ('trench coat', 'outerwear', 'lr', 'classic vintage', '*', 1, ''),
    ('rain jacket', 'outerwear', 'r', '*', '*', 0, 'style'),
    ('shearling-lined jacket', 'outerwear', 'k', 'edgy vintage', '*', 2, 'leather'),
    ('long cashmere coat', 'outerwear', 'k', 'classic', '*', 3, 'style'),
    ('light windbreaker', 'outerwear', 'l', 'sporty', '*', 0, 'style'),
    ('white sneakers', 'shoes', 'cw', '*', '*', 0, ''),
    ('running shoes', 'shoes', 'ca', 'sporty', '*', 0, 'style'),
    ('ankle boots', 'shoes', 'cwo', '*', '*', 0, 'leather'),
    ('combat boots', 'shoes', 'co', 'edgy', '*', 0, ''),
    ('loafers', 'shoes', 'cw', 'preppy classic', '*', 0, 'leather'),
    ('ballet flats', 'shoes', 'cw', 'classic vintage', 'f', 0, 'style'),
    ('strappy heels', 'shoes', 'o', 'classic', 'f', 0, 'style'),
    ('leather sandals', 'shoes', 'c', 'boho', '*', 0, ''),
    ('canvas high-tops', 'shoes', 'c', 'edgy vintage', '*', 0, 'style'),
    ('brogues', 'shoes', 'wo', 'classic preppy vintage', '*', 0, 'leather'),
    ('rain boots', 'shoes', 'r', 'cozy', '*', 0, 'style'),
    ('designer heels', 'shoes', 'o', 'classic', 'f', 3, ''),
    ('dress shoes', 'shoes', 'wo', 'classic minimal', 'm', 0, 'leather'),
    ('knit beanie', 'accessory', 'kc', 'cozy sporty edgy', '*', 0, 'style'),
    ('wool scarf', 'accessory', 'k', '*', '*', 0, 'style'),
    ('baseball cap', 'accessory', 'c', 'sporty', '*', 0, 'style'),
    ('canvas tote bag', 'accessory', 'c', 'boho minimal', '*', 0, ''),
    ('leather crossbody bag', 'accessory', 'co', 'classic', '*', 1, 'leather'),
    ('designer handbag', 'accessory', 'o', 'classic', 'f', 3, ''),
    ('silk scarf', 'accessory', 'wo', 'classic vintage', 'f', 2, 'style'),
    ('sunglasses', 'accessory', 'c', '*', '*', 0, ''),
    ('wristwatch', 'accessory', 'w', 'classic preppy', '*', 1, ''),
    ('silver hoop earrings', 'accessory', 'co', '*', 'f', 0, ''),
    ('layered necklaces', 'accessory', 'co', 'boho', '*', 0, ''),
    ('studded belt', 'accessory', 'c', 'edgy', '*', 0, ''),
    ('wide-brimmed hat', 'accessory', 'c', 'boho vintage', '*', 0, 'style'),
    ('backpack', 'accessory', 'c', 'sporty minimal', '*', 0, 'style'),
    ('leggings', 'active', 'a', '*', 'f', 0, 'style'),
    ('running shorts', 'active', 'a', '*', '*', 0, 'style'),
    ('moisture-wicking tee', 'active', 'a', '*', '*', 0, 'style'),
    ('track jacket', 'active', 'a', 'sporty vintage', '*', 0, 'style'),
    ('sweatpants', 'lounge', 'h', '*', '*', 0, 'style'),
    ('oversized sweatshirt', 'lounge', 'h', '*', '*', 0, 'style'),
    ('fuzzy socks', 'lounge', 'h', 'cozy', '*', 0, 'style'),
    ('worn-in joggers', 'lounge', 'h', 'sporty cozy', '*', 0, 'style'),
    ('fluffy robe', 'lounge', 'h', 'cozy classic', '*', 0, 'style'),
    ('flannel pajamas', 'sleep', 's', '*', '*', 0, 'style'),
    ('old T-shirt to sleep in', 'sleep', 's', '*', '*', 0, ''),
    ('cotton pajama set', 'sleep', 's', 'classic preppy', '*', 0, 'style'),
    ('silk pajamas', 'sleep', 's', 'classic', '*', 3, 'style'),
)
# Settings before the modern era (or fantasy ones): fewer, plainer things.
OTHER_PIECES = (
    ('linen shirt', 'top', 'cw', '*', '*', 0, 'style'),
    ('wool tunic', 'top', 'cw', '*', '*', 0, 'style'),
    ('embroidered blouse', 'top', 'co', 'boho vintage classic', 'f', 1, 'style'),
    ('fine silk shirt', 'top', 'o', 'classic', '*', 2, 'style'),
    ('wool breeches', 'bottom', 'cw', '*', 'm', 0, 'style'),
    ('plain trousers', 'bottom', 'cw', '*', '*', 0, 'style'),
    ('wool skirt', 'bottom', 'cw', '*', 'f', 0, 'style'),
    ('everyday wool gown', 'dress', 'cw', '*', 'f', 0, 'style'),
    ('linen kirtle', 'dress', 'c', 'boho cozy', 'f', 0, 'style'),
    ('fine silk gown', 'dress', 'o', 'classic', 'f', 2, 'style'),
    ('velvet doublet', 'suit', 'o', 'classic edgy', 'm', 2, 'style'),
    ('waistcoat', 'layer', 'cwo', 'classic preppy vintage', '*', 0, 'style'),
    ('heavy wool cloak', 'outerwear', 'kl', '*', '*', 0, 'style'),
    ('waxed cape', 'outerwear', 'r', '*', '*', 0, 'style'),
    ('fur-trimmed mantle', 'outerwear', 'k', 'classic', '*', 3, 'style'),
    ('leather boots', 'shoes', 'cwo', '*', '*', 0, 'leather'),
    ('riding boots', 'shoes', 'co', 'classic sporty', '*', 1, 'leather'),
    ('soft slippers', 'lounge', 'h', '*', '*', 0, 'style'),
    ('wide-brimmed hat', 'accessory', 'c', '*', '*', 0, 'style'),
    ('wool shawl', 'accessory', 'k', '*', '*', 0, 'style'),
    ('leather belt with a pouch', 'accessory', 'c', '*', '*', 0, ''),
    ('silver brooch', 'accessory', 'o', 'classic vintage', '*', 2, ''),
    ('pair of riding gloves', 'accessory', 'k', '*', '*', 1, 'leather'),
    ('loose house robe', 'lounge', 'h', '*', '*', 0, 'style'),
    ('linen nightshirt', 'sleep', 's', '*', '*', 0, ''),
)
# The 1920s: drop waists and cloche hats, three-piece suits and fedoras.
JAZZ_AGE_PIECES = (
    ('cotton shirtwaist blouse', 'top', 'cw', '*', 'f', 0, 'style'),
    ('collared work shirt', 'top', 'cw', '*', 'm', 0, 'style'),
    ('knitted sweater vest', 'top', 'c', 'preppy cozy vintage', '*', 0, 'style'),
    ('cable-knit cardigan', 'top', 'ch', 'cozy classic', '*', 0, 'style'),
    ('silk crepe blouse', 'top', 'wo', 'classic', 'f', 2, 'style'),
    ('starched dress shirt with a detachable collar', 'top', 'wo', 'classic preppy', 'm', 1, 'style'),
    ('pleated wool skirt', 'bottom', 'cw', '*', 'f', 0, 'style'),
    ('Oxford bags', 'bottom', 'c', 'preppy edgy', 'm', 1, 'style'),
    ('wool trousers with braces', 'bottom', 'cw', '*', 'm', 0, 'style'),
    ('plus-fours', 'bottom', 'c', 'sporty preppy', 'm', 1, 'style'),
    ('drop-waist day dress', 'dress', 'cw', '*', 'f', 0, 'style'),
    ('cotton house dress', 'dress', 'ch', 'cozy minimal', 'f', 0, 'style'),
    ('beaded flapper dress', 'dress', 'o', 'edgy classic', 'f', 1, 'style'),
    ('silk evening gown', 'dress', 'o', 'classic', 'f', 3, 'style'),
    ('three-piece wool suit', 'suit', 'wo', '*', 'm', 0, 'style'),
    ('pinstripe double-breasted suit', 'suit', 'wo', 'classic edgy', 'm', 2, 'style'),
    ('tuxedo', 'suit', 'o', 'classic', 'm', 2, ''),
    ('knitted cardigan jacket', 'layer', 'cw', 'cozy boho', 'f', 0, 'style'),
    ('tweed sport coat', 'layer', 'cw', 'preppy classic vintage', 'm', 1, 'style'),
    ('wool overcoat', 'outerwear', 'kl', '*', '*', 0, 'style'),
    ('belted trench coat', 'outerwear', 'r', '*', '*', 1, ''),
    ('raccoon coat', 'outerwear', 'k', 'preppy edgy', '*', 2, ''),
    ('fur-collared wrap coat', 'outerwear', 'ko', 'classic', 'f', 3, 'style'),
    ('Mary Jane shoes', 'shoes', 'cwo', '*', 'f', 0, 'leather'),
    ('T-strap dancing shoes', 'shoes', 'o', 'classic edgy', 'f', 1, ''),
    ('Oxford shoes', 'shoes', 'cwo', '*', 'm', 0, 'leather'),
    ('two-tone spectator shoes', 'shoes', 'co', 'edgy preppy', 'm', 1, ''),
    ('work boots', 'shoes', 'cw', 'minimal', '*', 0, 'leather'),
    ('galoshes', 'shoes', 'r', '*', '*', 0, ''),
    ('cloche hat', 'accessory', 'cwk', '*', 'f', 0, 'style'),
    ('felt fedora', 'accessory', 'cwk', '*', 'm', 0, 'style'),
    ('straw boater', 'accessory', 'c', 'preppy classic', 'm', 0, ''),
    ('newsboy cap', 'accessory', 'c', 'cozy vintage', '*', 0, 'style'),
    ('long pearl necklace', 'accessory', 'o', 'edgy classic boho', 'f', 0, ''),
    ('beaded headband', 'accessory', 'o', 'edgy boho', 'f', 1, ''),
    ('silk necktie', 'accessory', 'wo', '*', 'm', 0, 'style'),
    ('kid gloves', 'accessory', 'k', 'classic', '*', 1, 'leather'),
    ('silk kimono robe', 'lounge', 'h', 'classic boho', 'f', 1, 'style'),
    ('flannel dressing gown', 'lounge', 'h', '*', '*', 0, 'style'),
    ('carpet slippers', 'lounge', 'h', '*', '*', 0, ''),
    ('cotton nightgown', 'sleep', 's', '*', 'f', 0, ''),
    ('striped pajamas', 'sleep', 's', '*', '*', 0, 'style'),
)
PALETTES = {
    'classic': ('navy', 'camel', 'cream', 'charcoal', 'black', 'white', 'burgundy'),
    'sporty': ('heather grey', 'black', 'navy', 'white', 'cobalt', 'red'),
    'boho': ('rust', 'mustard', 'sage', 'cream', 'terracotta', 'olive'),
    'edgy': ('black', 'charcoal', 'deep red', 'olive', 'washed-black'),
    'cozy': ('oatmeal', 'soft grey', 'dusty pink', 'forest green', 'cream', 'chocolate brown'),
    'preppy': ('navy', 'white', 'kelly green', 'pale blue', 'red', 'khaki'),
    'vintage': ('mustard', 'brown', 'burgundy', 'cream', 'bottle green', 'rust'),
    'minimal': ('black', 'white', 'grey', 'navy', 'beige'),
    'denim': ('dark-wash', 'light-wash', 'black', 'mid-wash'),
    'leather': ('brown', 'black', 'tan', 'cognac'),
    'other': ('undyed', 'brown', 'grey', 'russet', 'dark green', 'woad-blue', 'madder-red'),
    'jazz-age': ('black', 'navy', 'dove grey', 'cream', 'champagne', 'plum', 'bottle green', 'camel', 'rose'),
}
STYLE_WORDS = {
    'classic': ('classic', 'elegant', 'polished', 'refined', 'sophisticated', 'put-together', 'poised', 'graceful',
                'timeless', 'formal'),
    'sporty': ('athletic', 'sporty', 'runner', 'running', 'gym', 'fitness', 'hiking', 'outdoors', 'climbing',
               'soccer', 'basketball', 'yoga', 'cycling', 'surf', 'swimming', 'marathon'),
    'boho': ('artsy', 'artistic', 'free-spirited', 'bohemian', 'boho', 'dreamy', 'hippie', 'whimsical', 'poetry',
             'gardening', 'festivals', 'spiritual'),
    'edgy': ('punk', 'edgy', 'rebellious', 'goth', 'gothic', 'rock', 'tattoo', 'tattooed', 'grunge', 'metal',
             'sarcastic', 'brooding', 'moody'),
    'cozy': ('cozy', 'cosy', 'homebody', 'laid-back', 'easygoing', 'relaxed', 'gentle', 'introvert', 'introverted',
             'soft-spoken', 'knitting', 'baking', 'comfort'),
    'preppy': ('preppy', 'ambitious', 'organized', 'organised', 'tidy', 'driven', 'type-a', 'perfectionist', 'golf',
               'tennis', 'sailing', 'competitive'),
    'vintage': ('vintage', 'retro', 'thrift', 'thrifting', 'antique', 'antiques', 'nostalgic', 'old-fashioned',
                'vinyl', 'jazz', 'swing'),
    'minimal': ('minimalist', 'minimal', 'practical', 'no-nonsense', 'understated', 'pragmatic', 'efficient',
                'reserved', 'stoic', 'simple'),
}
FASHION_WORDS = ('fashion', 'stylish', 'clothes', 'clothing', 'shopping', 'glamorous', 'glam', 'trendy', 'vain',
                 'makeup', 'chic', 'outfits', 'well-dressed', 'designer')
PLAIN_WORDS = ('minimalist', 'frugal', 'thrifty', 'no-nonsense', 'scruffy', 'unfussy', 'low-maintenance',
               'practical')
# What they wear to work, by career (companion/world/data/careers.json): a dress code, and the
# pieces that come with it. Kit slots: 'set' is a whole outfit, the rest stand in for their own.
CAREER_CODES = {
    'registered-nurse': 'scrubs', 'night-nurse': 'scrubs', 'physician-resident': 'scrubs-coat',
    'pharmacist': 'lab', 'medical-researcher': 'lab', 'biotech-scientist': 'lab', 'biologist': 'field',
    'software-engineer': 'casual', 'data-analyst': 'business-casual', 'ux-designer': 'creative',
    'graphic-designer': 'creative', 'financial-analyst': 'business', 'accountant': 'business',
    'paralegal': 'business', 'finance-banker': 'business', 'government-analyst': 'business',
    'real-estate-agent': 'business', 'defense-engineer': 'business-casual', 'teacher': 'smart-casual',
    'professor': 'smart-casual', 'social-worker': 'smart-casual', 'graduate-student': 'casual',
    'undergraduate': 'casual', 'journalist': 'business-casual', 'marketing-coordinator': 'business-casual',
    'event-planner': 'business-casual', 'barista': 'apron', 'baker': 'kitchen', 'line-cook': 'kitchen',
    'bartender': 'service', 'server': 'service', 'hotel-front-desk': 'front-desk', 'casino-dealer': 'dealer',
    'retail-associate': 'retail', 'musician': 'creative', 'performer': 'creative', 'actor': 'creative',
    'fashion-assistant': 'fashion', 'port-logistics': 'trades', 'construction-trades': 'trades',
    'military-sailor': 'military', 'fitness-trainer': 'trainer', 'surf-instructor': 'water',
    'lifeguard': 'lifeguard', 'tour-guide': 'casual',
}
# dress code: (how it reads, kit pieces as (name, slot), occasion their own clothes need at work)
CODES = {
    'scrubs': ('scrubs', (('{c} scrubs', 'set'), ('{c} scrubs', 'set'), ('cushioned nursing clogs', 'shoes')), 'w'),
    'scrubs-coat': ('scrubs and a white coat', (('{c} scrubs', 'set'), ('{c} scrubs', 'set'),
                                                ('a white coat with a stethoscope in the pocket', 'layer'),
                                                ('cushioned sneakers', 'shoes')), 'w'),
    'lab': ('business casual under a lab coat', (('a white lab coat', 'layer'),), 'w'),
    'field': ('practical field clothes', (('a many-pocketed field vest', 'layer'), ('waterproof field boots', 'shoes')),
              'c'),
    'casual': ('whatever is comfortable', (), 'c'),
    'business-casual': ('business casual', (), 'w'),
    'business': ('business clothes', (), 'w'),
    'smart-casual': ('smart casual', (), 'w'),
    'creative': ('their own style', (), 'c'),
    'fashion': ('their sharpest outfits', (), 'o'),
    'apron': ('their own clothes under a café apron', (('a canvas barista apron', 'layer'),), 'c'),
    'kitchen': ('chef whites', (('a white chef jacket', 'top'), ('checked chef pants', 'bottom'),
                                ('non-slip kitchen clogs', 'shoes')), 'c'),
    'service': ('all black', (('a black button-down shirt', 'top'), ('black trousers', 'bottom'),
                              ('a black waist apron', 'layer'), ('black non-slip shoes', 'shoes')), 'w'),
    'front-desk': ('a hotel uniform', (('a hotel uniform: navy blazer, white shirt and a name badge', 'set'),
                                       ('polished black work shoes', 'shoes')), 'w'),
    'dealer': ("a dealer's uniform", (("a dealer's uniform: white shirt, black vest and bow tie", 'set'),
                                      ('polished black work shoes', 'shoes')), 'w'),
    'retail': ('a store polo with a name tag', (('a store polo with a name tag', 'top'),), 'c'),
    'trades': ('work gear', (('a hi-vis vest', 'layer'), ('heavy canvas work pants', 'bottom'),
                             ('steel-toe boots', 'shoes'), ('a scuffed hard hat', 'extra')), 'c'),
    'military': ('a uniform', (('a navy working uniform', 'set'), ('black uniform boots', 'shoes'),
                               ('dress whites for ceremonies', 'formal')), 'w'),
    'trainer': ('gym clothes', (("a black trainer's tee with the gym's logo", 'top'), ('black training joggers', 'bottom'),
                                ('cross-training shoes', 'shoes')), 'a'),
    'water': ('a wetsuit', (('a full wetsuit', 'set'),), 'c'),
    'lifeguard': ('a lifeguard uniform', (('a red lifeguard uniform with a whistle', 'set'),), 'c'),
}
KIT_COLORS = ('navy', 'ceil blue', 'wine', 'charcoal', 'teal')
# Sectors whose dress code fits when the career is not in the list.
SECTOR_CODES = {'healthcare': 'scrubs', 'finance': 'business', 'legal': 'business', 'tech': 'casual',
                'hospitality': 'service', 'education': 'smart-casual', 'arts': 'creative'}

# Clothing named in their appearance ("always in a battered leather jacket") becomes a favourite.
GARMENTS = {
    'jacket': 'layer', 'blazer': 'layer', 'coat': 'outerwear', 'parka': 'outerwear', 'cloak': 'outerwear',
    'sweater': 'top', 'jumper': 'top', 'hoodie': 'top', 'cardigan': 'top', 'shirt': 'top', 'blouse': 'top',
    'tee': 'top', 't-shirt': 'top', 'flannel': 'top', 'turtleneck': 'top', 'vest': 'layer', 'waistcoat': 'layer',
    'jeans': 'bottom', 'skirt': 'bottom', 'trousers': 'bottom', 'overalls': 'bottom', 'dress': 'dress',
    'suit': 'suit', 'boots': 'shoes', 'sneakers': 'shoes', 'trainers': 'shoes', 'heels': 'shoes',
    'loafers': 'shoes', 'sandals': 'shoes', 'scarf': 'accessory', 'hat': 'accessory', 'cap': 'accessory',
    'beanie': 'accessory', 'beret': 'accessory', 'bandana': 'accessory', 'necklace': 'accessory',
    'earrings': 'accessory', 'bracelet': 'accessory', 'ring': 'accessory', 'watch': 'accessory',
    'tie': 'accessory', 'pendant': 'accessory', 'locket': 'accessory',
}
