"""Reference pictures for a character's LoRA: the Prepare and Review steps.

The user adds each picture deliberately; nothing is collected from folders. Every picture keeps
its original file, a rights choice and a source note, and is either a training image, a held-out
evaluation reference, or excluded with a reason. Captions start as editable suggestions built
from the character's appearance text; nothing looks at the picture to write them.
"""
import hashlib

from companion.characters import require_current
from companion.database import decode, encode, identifier, many, one
from companion.errors import DomainError, require
from companion.images.adapters.base import AdapterError
from companion.images.storage import sniff
from companion.lora import files

MAX_BYTES = 30 * 1024 * 1024
# AI Toolkit reads JPEG and PNG datasets.
TYPES = {'png': 'image/png', 'jpg': 'image/jpeg'}
NEAR = 6
MIN_TRAINING = 5
RECOMMENDED = (20, 40)
RIGHTS = {'own_work': 'Made by you', 'commissioned': 'Commissioned for you', 'licensed': 'Licensed for this use',
          'generated': 'Generated by you', 'unknown': 'Not stated'}


def directory(database):
    return files.folder(database, 'references')


def hamming(first: str | None, second: str | None) -> int | None:
    if not first or not second:
        return None
    try:
        return bin(int(first, 16) ^ int(second, 16)).count('1')
    except ValueError:
        return None


def view(row: dict) -> dict:
    return {**row, 'crop': decode(row['crop']), 'has_crop': row['crop_file'] is not None,
            'rights_label': RIGHTS[row['rights']]}


def rows(connection) -> list[dict]:
    companion = require_current(connection)
    return many(connection, 'SELECT * FROM lora_references WHERE companion_id=? ORDER BY created_at, rowid',
                (companion['id'],))


def near_pairs(items: list[dict]) -> list[tuple[dict, dict]]:
    pairs = []
    for index, first in enumerate(items):
        for second in items[index + 1:]:
            distance = hamming(first['dhash'], second['dhash'])
            if distance is not None and distance <= NEAR:
                pairs.append((first, second))
    return pairs


def review(items: list[dict]) -> dict:
    """What stands between this dataset and training, and what is only advice."""
    training = [item for item in items if item['role'] == 'train']
    evaluation = [item for item in items if item['role'] == 'evaluation']
    blocking, advice = [], []
    if len(training) < MIN_TRAINING:
        blocking.append(f'Add at least {MIN_TRAINING} training pictures ({len(training)} so far).')
    elif len(training) < RECOMMENDED[0]:
        advice.append(f'Community guides for Krea 2 use {RECOMMENDED[0]} to {RECOMMENDED[1]} pictures, '
                      'including a few full-body shots.')
    unknown = [item for item in training if item['rights'] == 'unknown']
    if unknown:
        blocking.append(f'Say where {len(unknown)} training picture(s) came from and that you may use them.')
    uncaptioned = [item for item in training if not item['caption'].strip()]
    if uncaptioned:
        advice.append(f'{len(uncaptioned)} training picture(s) have no caption; they train on the trigger word only.')
    if not evaluation:
        advice.append('Hold back one or two pictures as evaluation references to compare results against.')
    for first, second in near_pairs([item for item in items if item['role'] != 'excluded']):
        roles = {first['role'], second['role']}
        names = f"{first['original_name'] or first['id'][:8]} and {second['original_name'] or second['id'][:8]}"
        if roles == {'train', 'evaluation'}:
            blocking.append(f'{names} look nearly identical, but one trains and one evaluates. An evaluation '
                            'reference must not be a copy of a training picture.')
        else:
            advice.append(f'{names} look nearly identical; consider excluding one.')
    return {'training': len(training), 'evaluation': len(evaluation),
            'excluded': sum(item['role'] == 'excluded' for item in items), 'blocking': blocking, 'advice': advice,
            'ready': not blocking}


def listing(database) -> dict:
    with database.connect() as connection:
        items = rows(connection)
    duplicates = {}
    for first, second in near_pairs(items):
        duplicates.setdefault(second['id'], first['id'])
    folder = directory(database)
    return {'references': [{**view(item), 'similar_to': duplicates.get(item['id']),
                            'missing': not (folder / item['file']).is_file()} for item in items],
            'review': review(items)}


def get(connection, reference_id) -> dict:
    companion = require_current(connection)
    return one(connection, 'SELECT * FROM lora_references WHERE id=? AND companion_id=?',
               (reference_id, companion['id']))


def checked_image(data: bytes) -> tuple[str, int, int]:
    try:
        kind, width, height = sniff(data)
    except AdapterError as error:
        raise DomainError('Add a PNG or JPEG picture.', 422) from error
    require(kind in TYPES, 'Save this picture as PNG or JPEG first; the trainer reads those two formats.', 422)
    require(64 <= width <= 12000 and 64 <= height <= 12000, 'This picture is too small or too large to use.', 422)
    return kind, width, height


def add(database, data: bytes, original_name='', dhash=None) -> dict:
    require(len(data) <= MAX_BYTES, 'This picture is larger than 30 MB.', 413)
    kind, width, height = checked_image(data)
    digest = hashlib.sha256(data).hexdigest()
    with database.connect(write=True) as connection:
        companion = require_current(connection)
        existing = connection.execute('SELECT id FROM lora_references WHERE companion_id=? AND sha256=?',
                                      (companion['id'], digest)).fetchone()
        if existing:
            raise DomainError('This exact picture is already in the set.', 409, 'duplicate')
        reference_id = identifier()
        name = f'{reference_id}.{kind}'
        target = directory(database) / name
        partial = target.with_name(name + '.partial')
        partial.write_bytes(data)
        partial.replace(target)
        timestamp = database.now()
        connection.execute(
            'INSERT INTO lora_references (id, companion_id, file, original_name, media_type, sha256, dhash, width, '
            'height, bytes, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)',
            (reference_id, companion['id'], name, original_name[:200], TYPES[kind], digest, clean_hash(dhash),
             width, height, len(data), timestamp, timestamp))
        return view(get(connection, reference_id))


def clean_hash(value) -> str | None:
    if isinstance(value, str) and len(value) == 16 and all(char in '0123456789abcdef' for char in value.lower()):
        return value.lower()
    return None


def update(database, reference_id, body) -> dict:
    changes = body.model_dump(exclude_none=True)
    with database.connect(write=True) as connection:
        row = get(connection, reference_id)
        if 'caption' in changes:
            changes['caption_origin'] = 'edited' if changes['caption'].strip() else 'empty'
        if changes.get('role') and changes['role'] != 'excluded':
            changes.setdefault('exclusion_reason', '')
        if changes.get('role') == 'excluded':
            require(changes.get('exclusion_reason', row['exclusion_reason']).strip(),
                    'Say why this picture is excluded, so the record stays clear later.')
        if not changes:
            return view(row)
        assignments = {**changes, 'updated_at': database.now()}
        columns = ', '.join(f'{key}=?' for key in assignments)
        connection.execute(f'UPDATE lora_references SET {columns} WHERE id=?', (*assignments.values(), reference_id))
        return view(get(connection, reference_id))


def suggestion(appearance: str) -> str:
    """`[trigger]` is replaced with the trigger word by AI Toolkit."""
    text = ' '.join(appearance.split())[:300].rstrip('.')
    return f'[trigger], {text}' if text else '[trigger]'


def suggest_captions(database, replace_suggested=True) -> dict:
    """Fill empty captions (and earlier suggestions) from the appearance text. Captions the user
    wrote are never overwritten."""
    with database.connect(write=True) as connection:
        companion = require_current(connection)
        text = suggestion(companion['version']['definition'].get('appearance', ''))
        origins = ('empty', 'suggested') if replace_suggested else ('empty',)
        connection.execute(
            f"UPDATE lora_references SET caption=?, caption_origin='suggested', updated_at=? WHERE companion_id=? "
            f"AND caption_origin IN ({', '.join('?' for _ in origins)})",
            (text, database.now(), companion['id'], *origins))
    return listing(database)


def set_crop(database, reference_id, crop: dict, data: bytes) -> dict:
    """A crop is drawn in the interface and saved as a separate copy; the original stays as it was."""
    kind, _width, _height = checked_image(data)
    with database.connect(write=True) as connection:
        row = get(connection, reference_id)
        name = f'{reference_id}.crop.{kind}'
        target = directory(database) / name
        partial = target.with_name(name + '.partial')
        partial.write_bytes(data)
        partial.replace(target)
        if row['crop_file'] and row['crop_file'] != name:
            (directory(database) / row['crop_file']).unlink(missing_ok=True)
        connection.execute('UPDATE lora_references SET crop=?, crop_file=?, updated_at=? WHERE id=?',
                           (encode(crop), name, database.now(), reference_id))
        return view(get(connection, reference_id))


def clear_crop(database, reference_id) -> dict:
    with database.connect(write=True) as connection:
        row = get(connection, reference_id)
        if row['crop_file']:
            (directory(database) / row['crop_file']).unlink(missing_ok=True)
        connection.execute('UPDATE lora_references SET crop=NULL, crop_file=NULL, updated_at=? WHERE id=?',
                           (database.now(), reference_id))
        return view(get(connection, reference_id))


def remove(database, reference_id) -> dict:
    with database.connect(write=True) as connection:
        row = get(connection, reference_id)
        connection.execute('DELETE FROM lora_references WHERE id=?', (reference_id,))
    for name in (row['file'], row['crop_file']):
        if name:
            (directory(database) / name).unlink(missing_ok=True)
    return listing(database)


def path_of(database, reference_id, cropped=False):
    with database.connect() as connection:
        row = get(connection, reference_id)
    name = row['crop_file'] if cropped and row['crop_file'] else row['file']
    return files.inside(directory(database), name), row['media_type']
