// Display logic for the LoRA maker that needs no browser (docs/lora.md).
import type { Checkpoint, Crop, DatasetReview, EvalImage, Generation, PlannedShot, Rights, TrainingRun } from '../../types'

export const STEPS = [
  { id: 'prepare', label: 'Prepare' },
  { id: 'review', label: 'Review' },
  { id: 'configure', label: 'Configure' },
  { id: 'train', label: 'Train' },
  { id: 'evaluate', label: 'Evaluate' },
  { id: 'adopt', label: 'Adopt' },
] as const
export type Step = typeof STEPS[number]['id']

export const RIGHTS: { id: Rights; label: string }[] = [
  { id: 'unknown', label: 'Not stated yet' },
  { id: 'own_work', label: 'Made by me' },
  { id: 'commissioned', label: 'Commissioned for me' },
  { id: 'licensed', label: 'Licensed for this use' },
  { id: 'generated', label: 'Generated by me' },
]

/** A 64-bit difference hash from a 9×8 grayscale grid (row-major, 72 values), as 16 hex digits. */
export function dhash(gray: ArrayLike<number>): string {
  if (gray.length !== 72) throw new Error('dhash needs a 9×8 grid')
  let bits = ''
  for (let row = 0; row < 8; row++) {
    for (let column = 0; column < 8; column++) bits += gray[row * 9 + column] < gray[row * 9 + column + 1] ? '1' : '0'
  }
  let hex = ''
  for (let index = 0; index < 64; index += 4) hex += parseInt(bits.slice(index, index + 4), 2).toString(16)
  return hex
}

/** Luminance of RGBA pixel data, for `dhash`. */
export function grayscale(rgba: ArrayLike<number>): number[] {
  const gray: number[] = []
  for (let index = 0; index < rgba.length; index += 4) gray.push(0.299 * rgba[index] + 0.587 * rgba[index + 1] + 0.114 * rgba[index + 2])
  return gray
}

/** The crop in source pixels, kept inside the picture. */
export function cropPixels(crop: Crop, width: number, height: number) {
  const x = Math.round(Math.min(Math.max(crop.x, 0), 1) * width)
  const y = Math.round(Math.min(Math.max(crop.y, 0), 1) * height)
  return { x, y, width: Math.max(1, Math.min(Math.round(crop.width * width), width - x)), height: Math.max(1, Math.min(Math.round(crop.height * height), height - y)) }
}

export function reviewLine(review: DatasetReview): string {
  const counts = `${review.training} training, ${review.evaluation} held out for evaluation, ${review.excluded} excluded.`
  return review.ready ? `Ready to train: ${counts}` : `Not ready yet: ${counts}`
}

/** Progress exactly as the trainer reported it; nothing is estimated. */
export function progressLine(run: TrainingRun): string {
  const reported = run.progress_step !== null && run.progress_total ? `Step ${run.progress_step} of ${run.progress_total}, as the trainer reported.` : null
  if (run.status === 'running') return reported ?? 'Starting. Progress appears when the trainer reports it.'
  if (run.status === 'completed') return 'Finished. The adapter is ready to evaluate; nothing changes until you adopt it.'
  const saved = run.checkpoints.filter((item) => item.verified && !item.final).length
  const resume = run.resumable ? ` ${saved} verified checkpoint${saved === 1 ? '' : 's'} can be resumed.` : run.restartable ? ' No verified checkpoint, so it can only restart.' : ''
  return `${run.error ?? `${STATUS[run.status]}.`}${resume}`
}

const STATUS: Record<TrainingRun['status'], string> = { running: 'Training', completed: 'Finished', failed: 'Failed', cancelled: 'Cancelled', interrupted: 'Interrupted' }

export function checkpointLine(item: Checkpoint): string {
  const label = item.final ? `Final (step ${item.step})` : `Step ${item.step}`
  return item.verified ? `${label} · ${formatBytes(item.bytes)} · checked` : `${label} · failed the check: ${item.problem}`
}

export function formatBytes(bytes: number): string {
  if (bytes >= 1024 ** 3) return `${(bytes / 1024 ** 3).toFixed(1)} GB`
  if (bytes >= 1024 ** 2) return `${(bytes / 1024 ** 2).toFixed(1)} MB`
  return `${Math.max(1, Math.round(bytes / 1024))} KB`
}

/** Evaluation images as rows of one prompt, with the adapter and text-only versions side by side. */
export function evaluationRows(images: EvalImage[]): { key: string; label: string; lora?: EvalImage; text?: EvalImage }[] {
  const rows = new Map<string, { key: string; label: string; lora?: EvalImage; text?: EvalImage }>()
  for (const image of [...images].sort((first, second) => first.position - second.position)) {
    const row = rows.get(image.prompt_key) ?? { key: image.prompt_key, label: image.label }
    row[image.variant] = image
    rows.set(image.prompt_key, row)
  }
  return [...rows.values()]
}

export const TRIGGER_PATTERN = /^[A-Za-z0-9_-]{2,40}$/

/** One line for where a planned shot goes, or why it cannot be made. */
export function routeLine(shot: PlannedShot): string {
  if (!shot.backend) return shot.refusal ?? 'Cannot be made.'
  const tier = shot.tier === 'safe' ? '' : ` Classified ${shot.tier}${shot.reasons.length ? ` (${shot.reasons.join(', ')})` : ''}.`
  return `Goes to ${shot.backend.label}${shot.backend.local ? ' on this computer' : ''}.${tier}`
}

/** Progress of a generated set, counting only what happened. */
export function generationLine(generation: Generation): string {
  const { counts } = generation
  const parts = [`${counts.completed} made`]
  if (counts.failed) parts.push(`${counts.failed} failed`)
  const left = counts.queued + counts.running
  if (left) parts.push(`${left} to go`)
  if (counts.cancelled + counts.interrupted) parts.push(`${counts.cancelled + counts.interrupted} stopped`)
  if (counts.kept) parts.push(`${counts.kept} kept`)
  return `${parts.join(', ')}.`
}

/** The full prompt each shot sends, as the server composes it. */
export function composePrompt(style: string, base: string, shot: string): string {
  const trim = (text: string) => text.trim().replace(/\.+$/, '')
  return `${trim(style || 'Natural photograph')}. ${trim(base)}, ${trim(shot)}.`
}
